cache:
  directories:
    - node-modules
    - web/vendor
    - vendor

before_install:
  - make env
  - docker-compose pull

install:
  - docker-compose run npm
  - docker-compose run composer install --no-interaction
  - while ! docker-compose run web bin/console doctrine:query:sql "SELECT TRUE" > /dev/null 2>&1; do
      echo 'Waiting for postgres...'
      sleep 1;
    done;

script:
  - docker-compose run web make init cs-check test
