app_tag:
    resource: "@AppBundle/Controller/TagController.php"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

dashboard:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
