# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.import_type:
        class: AppBundle\Form\ImportType
        arguments: ['@session', '@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: AppBundle\Form\ImportType }
