# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        public: false

    AppBundle\DataFixtures\UserFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\Form\ImportType:
        arguments: { $importDir: '%import_dir%' }
        tags: [name: form.type]
    AppBundle\Form\UserFieldTypeExtension:
        tags: [{ name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }]

    AppBundle\Utils\FileImporter:
        arguments: { $importDir: '%import_dir%' }
        public: true
