# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.import_type:
        class: AppBundle\Form\ImportType
        tags:
            - { name: form.type, alias: AppBundle\Form\ImportType }
    app.util.file_importer:
        class: AppBundle\Utils\FileImporter
        arguments: ['@doctrine.orm.entity_manager']
